services:
  ### AS core network ###

  box_1:
    tty: true
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: client
    networks:
      reseau_box:
        ipv4_address: 120.0.33.2
      reseau_client_1:
        ipv4_address: 192.168.0.2

  box_2:
    tty: true
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: client
    networks:
      reseau_box:
        ipv4_address: 120.0.33.3
      reseau_client_2:
        ipv4_address: 192.168.0.2

  client_1:
    tty: true
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: quagga
    networks:
      reseau_client_1:
        ipv4_address: 192.168.0.6

  client_2:
    tty: true
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: base_image
    networks:
      reseau_client_1:
        ipv4_address: 192.168.0.7


networks:
  reseau_client_1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

  reseau_client_2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

  reseau_box:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.33.0/24

