services:
  ### AS core network ###

  box_1:
    tty: true
    volumes:
      - ./data/box_c1:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: box
    networks:
      reseau_box:
        ipv4_address: 120.0.33.11
      reseau_client_1:
        ipv4_address: 192.168.1.11

  box_2:
    tty: true
    volumes:
      - ./data/box_c2:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: box
    networks:
      reseau_box:
        ipv4_address: 120.0.33.12
      reseau_client_2:
        ipv4_address: 192.168.2.12

  client_1:
    tty: true
    volumes:
      - ./data/client_c1:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: client
    networks:
      reseau_client_1:
        ipv4_address: 192.168.1.254

  client_2:
    tty: true
    volumes:
      - ./data/client_c2:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: client
    networks:
      reseau_client_2:
        ipv4_address: 192.168.2.254

  client_site1:
    tty: true
    volumes:
      - ./data/client_site1:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: client
    networks:
      reseau_site1:
        ipv4_address: 120.0.36.13

  client_site2:
    tty: true
    volumes:
      - ./data/client_site2:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: client
    networks:
      reseau_site2:
        ipv4_address: 120.0.34.12

  routeur_1:
    tty: true
    volumes:
      - ./data/router_1:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: router
    networks:
      reseau_box:
        ipv4_address: 120.0.33.13
      reseau_1:
        ipv4_address: 120.0.40.11

  routeur_2:
    tty: true
    volumes:
      - ./data/router_2:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: router
    networks:
      reseau_2:
        ipv4_address: 120.0.32.74
      reseau_sites:
        ipv4_address: 120.0.32.139

  routeur_main:
    tty: true
    volumes:
      - ./data/router_main:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: router
    networks:
      reseau_1:
        ipv4_address: 120.0.40.12
      reseau_2:
        ipv4_address: 120.0.32.75

  routeur_site1:
    tty: true
    volumes:
      - ./data/router_site1:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: router
    networks:
      reseau_site1:
        ipv4_address: 120.0.36.12
      reseau_sites:
        ipv4_address: 120.0.32.140

  routeur_site2:
    tty: true
    volumes:
      - ./data/router_site2:/data
    extends:
      file: ./docker-compose-all.yml
      service: base
    image: router
    networks:
      reseau_site2:
        ipv4_address: 120.0.34.11
      reseau_sites:
        ipv4_address: 120.0.32.141


  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '8080:80'
    volumes:
    - ./data/web-entreprise:/data
    - ./website:/usr/local/apache2/htdocs
    networks:
      reseau_site1:
        ipv4_address: 120.0.36.51/22

dns_server:
  build: dns
  container_name: dns_server
  hostname:  dns_server
  networks:
    reseau_site1:
      ipv4_address: 120.0.36.51
  privileged: true
      
networks:
  reseau_client_1:

    ipam:
      config:
        - subnet: 192.168.1.0/24

  reseau_client_2:

    ipam:
      config:
        - subnet: 192.168.2.0/24

  reseau_box:

    ipam:
      config:
        - subnet: 120.0.33.0/24

  reseau_1:
    ipam:
      config:
        - subnet: 120.0.40.0/21

  reseau_2:
    ipam:
      config:
        - subnet: 120.0.32.64/26

  reseau_sites:
    ipam:
      config:
        - subnet: 120.0.32.128/25

  reseau_site1:
    ipam:
      config:
        - subnet: 120.0.36.0/22

  reseau_site2:
    ipam:
      config:
        - subnet: 120.0.34.0/23
